### ISSUE TITLE
Rainfall data

### ISSUE THREAD

**Issue by Jiadalee** [dt-woods/idf#1]
@dt-woods Hi, do you have an example of the time-series rainfall datasets? Thanks

**Comment by dt-woods** [comment]
URL: https://waterdata.usgs.gov/nc/nwis/inventory/?site_no=354057080362545
description: Contains 5-minute resolution rainfall data in CSV format for USGS rain gage at RO-149 PIEDMONT RS 1 NR BARBER, NC
USGS site: 354057080362545
Retrieved: 2019-04-10
Parameter: Precipitation, total, inches
Date range: 2009-10-01 01:00 EDT to 2019-04-10 09:55 EDT
Rows of data: 960109

DATA ACCESS
* Browse to URL
* Click Current / Historical Observations
* Check 00045 Precipitation
  Output format: Tab-separated
  Begin date: 2009-10-01
  End date: 2019-04-10
  Click Go 
* Right-click on page: Save page as "nwis.waterdata.usgs.gov"

NOTE: Identified 1095 rainfall events using 5 hour MIT

**Comment by Jiadalee** [comment]
@dt-woods hi, do you know how  idf.ipyn file read the .txt precipitation file?

**Comment by dt-woods** [comment]
The way it is set up, download the USGS rainfall data (nwis.waterdata.usgs.gov) and put it in the same directory as the idf.py script; it looks for it locally.

File names and directories are defined on L358-359.

**Comment by Jiadalee** [comment]
@dt-woods yes, the script can read this file now. However, it ends nothing. There is no IDF plots in my side

**Comment by Jiadalee** [comment]
@dt-woods what does the IDF curve looks like? I can't get the plots after I  finish the codes running..

**Comment by dt-woods** [comment]
@Jiadalee, see if the updated code works for you. It should write the IDF plot to a PNG image file. Mine looks like this (see image below).
![idf](https://user-images.githubusercontent.com/29642997/69597633-9f668180-0fd4-11ea-8bc9-0f1b9399ea44.png)

**Comment by Jiadalee** [comment]
@dt-woods It works now. Does this script work for other precipitation data from other web sources? Does this only work for the precipitation datasets from the USGS web?

**Comment by Jiadalee** [comment]
@dt-woods  I got an error showing  ' name input_path is not defined'...

**Comment by Jiadalee** [comment]
@dt-woods the IDF plot always keeps the same, although I use different precipitation datasets...

**Comment by dt-woods** [comment]
@Jiadalee, I've made some updates to help you on your way. There are now command-line arguments so you can choose the input file, whether or not to process it (e.g., if it was from USGS), whether or not to save IDF to PNG. 

To answer your question, yes, you can use any rainfall data; except it needs to be correctly formatted. I've updated the README to show example input formats.

**Comment by Jiadalee** [comment]
@dt-woods  Running the updated script gives me an error below:

> Using: nbAgg

usage: ipykernel_launcher.py [-h] [--usgs] [--make_regular] [--save_plot]
                             [--verbose]
                             file
ipykernel_launcher.py: error: unrecognized arguments: -f

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by Jiadalee** [comment]
@dt-woods Thank you for your updates! Unfortunately, I'm not familiar with the command-line.  Can you give me an example about how to run this command-line? Thanks

**Comment by Jiadalee** [comment]
@dt-woods by the way, where should I go to modify the codes to read the 'input file' in the updated script? I find it is different from the previous one, regarding input file reading.

**Comment by dt-woods** [comment]
No updating the code is required. Everything can run from the command line. Let's say you have your rainfall data `rainfall.txt` and the python code `idf.py` in the same directory. Open a command line (or terminal) and navigate to your folder that has the two files. If you two files are in C:\Workspace\IDF, then type: `cd C:\Workspace\IDF`. From there, run the following:
```
python idf.py --save_plot rainfall.txt
``` 
If your rainfall data was downloaded for a USGS rain gage station (e.g., `usgs_waterdata.gov`), then you would use the following command:
```
python idf.py --usgs --save_plot usgs_waterdata.gov
```
If you are still having difficulties, please let me know what operating system you are using, what version of python you are using, and how you run the code on your computer; otherwise, I fear I don't know how to help.

**Comment by Jiadalee** [comment]
@dt-woods Yes. I did what you typed to me. For the usgs rainfall data, I think we need to type 'usgs_waterdata.gov.txt'. If we missed the suffix .txt， it will show an error 

> can't find input file usgs_waterdata.gov

However, even though, I typed 'usgs_waterdata.gov.txt',  running this command-line still gives me an error:

> Could not write to the output file

See the attached screenshot of the error in my terminal. I used Win10 operating system and Python 3
![error](https://user-images.githubusercontent.com/30839207/69768942-f63c9a00-113f-11ea-8605-4a1c3dd3222d.png)

**Comment by dt-woods** [comment]
I see. It looks like your browser added the ".txt" when you downloaded the file. This is okay and nice job catching it! If you type `dir` you will see all the files in the current directory. If you don't like Windows hiding file extension from you in File Explorer, I recommend unhiding them (see [here](https://www.thewindowsclub.com/show-file-extensions-in-windows) for instructions). I'll look into the error. In the meantime, can you check a few things for me?

1. Do you see a file called usgs_waterdata.gov.txt.csv?
2. What do you see when you type `python -V`?

**Comment by Jiadalee** [comment]
@dt-woods 

1. Yes, I got the usgs_waterdata.gov.txt.csv file;
2. It shows python 2.7.15

**Comment by Jiadalee** [comment]
@dt-woods Let me try it in Python 3. I'm sorry about that.

**Comment by Jiadalee** [comment]
@dt-woods Python 2 works now in my side. I can get the idf plot and also a new .csv file. Thank you very much!

**Comment by dt-woods** [comment]
Glad to hear it. I'm going to close this issue. Let me know if you run into any problems. Thanks for your feedback.
