### ISSUE TITLE
rainfall format for example 2

### ISSUE THREAD

**Issue by Jiadalee** [dt-woods/idf#2]
@dt-woods Hi, I tested the example 2 by using my own two-column rainfall datasets. The format for the rainfall data is:

> datetime	rainfall

> 10/1/2009 1:00	0

> 10/1/2009 1:05	0.01

> 10/1/2009 1:10	0.01

However, the terminal always shows an error saying 'can't read the input file. Check the format':
![image](https://user-images.githubusercontent.com/30839207/69919493-90e7f200-143a-11ea-8f55-65f4730ca07e.png)

I'm wondering which rainfall format is correct for example 2. Do I need to add a comma between 'datetime' and 'rainfall'? Thanks!

**Comment by dt-woods** [comment]
@Jiadalee, 

Yeah, you need a comma and no space between the minutes of your timestamp and the rainfall amount.

**Comment by Jiadalee** [comment]
@dt-woods Yes. I insert a comma and delete the space. However, it still gives me an error. Please see the screenshot attached.
![image](https://user-images.githubusercontent.com/30839207/73799785-27ef6400-4774-11ea-81df-9d93608f3dbb.png)

**Comment by dt-woods** [comment]
I think the issue is that your data file ends with a rain event that has no zero. One possible fix would be to extend your dataset til the current rain event ends; alternatively, you could just add a dummy timestamp at the end of you data file with rainfall amount zero. See if that helps.

**Comment by Jiadalee** [comment]
Yes. It works now by adding a dummy timestamp at the end of the data file with zero amount of rainfall. One more question: Can command '--make_regular' transfer the timestamp format? like transferring "YYYY/MM/DD HH:MM:SS" to "YYYY-MM-DD HH:MM:SS"?

**Comment by dt-woods** [comment]
As it stands, no. The `make_regular` flag will take timestamps from a dataset that have irregular intervals, e.g.,

```
2002-02-01 01:00:00,0.0
2002-02-01 01:05:10,0.0
2002-02-01 01:06:30,0.0
2002-02-01 01:09:15,0.0
```

and attempt to create an equal time series interval, e.g.,

```
2002-02-01 01:00:00,0.0
2002-02-01 01:05:00,0.0
2002-02-01 01:10:00,0.0
```

To correct the data format of your input file, you can use a find-replace function to replace all "/" with "-" or import your data into a spread sheet program and apply the time stamp formatting before exporting to CSV or write a script that does this for you. Sorry I don't have a helper function ready for you!

**Comment by Jiadalee** [comment]
Thank you for answering my question. I will do that later.
